apiVersion: v1
kind: Service
metadata:
  name: week-9-1021-service
  labels:
    app: week-9-1021
  namespace: group-3
spec:
  ports:
  - name: week-9-1021-port
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: week-9-1021
  type: LoadBalancer
status:
  loadBalancer: {}