name: Retag Image with Github commit id
run-name: Build Image

on:
  push:
    branches: ["develop"]

jobs:
  update_tag_with_committid:

    name: Update tag image with Git commitID
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Get Git CommitId  
        run: |
            echo "commit_id=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
            echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
            source $GITHUB_ENV
            echo "branch: " $branch
            echo "commitid: " $commit_id
            
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Echo CommitId
        run: |
             $commit_id
             
      - name: Build and Push with tag = Git CommitId
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/week-9-1021:$commit_id
