name: Retag Image with Release Version
run-name: Build and Push Image with rc

on:

  push:
    branches: ["develop"]

jobs:
  update_tag_with_release_version:

    name: Update tag image with Release Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: echo hello
        run: echo "hello main action"

      - name: Get Release Version
        run: |
              version=$(jq -r '.version' package.json)
              echo "Package version is: $version"
              echo "release_version=$version" >> $GITHUB_ENV
      
      - name: Set output named RELEASE_VERSION
        id: release-version
        run: echo "RELEASE_VERSION=$release_version" >> "$GITHUB_OUTPUT"

      - name: Echo RELEASE_VERSION
        run: ${{ steps.release-version.outputs.RELEASE_VERSION }}

#have docker imagec(pull) > retag (docker tag)