name: Retag Image with Release Version
run-name: Build and Push Image with rc

on:

  pull_request:
    branches: ["develop"]

jobs:
  update_tag_with_release_version:

    name: Update tag image with Release Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: echo hello
        run: echo "hello main action"

      - name: Get Release Version
        run: |
              echo "package=$(cat ./package.json)" >> $GITHUB_ENV
              echo "package file: " $package
# - run: |
#     echo '${{ fromJson(env.PACKAGE_JSON).version }}'

#have docker imagec(pull) > retag (docker tag)